name: Build and Release
on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Use .NET 8.0
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      # Build the project
      - name: Build project
        run: dotnet build --configuration Release
      # Publish the application
      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish
      # Archive the published files
      - name: Create ZIP archive
        run: |
          mkdir artifacts
          Compress-Archive -Path ./publish/* -DestinationPath ./artifacts/StarCraftKeyManager.zip
      # Upload the artifact to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/StarCraftKeyManager.zip
          asset_name: StarCraftKeyManager.zip
          asset_content_type: application/zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Create a release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release contains the latest build of StarCraft Key Manager.
            Download the ZIP file below, extract it, and run the application.
          draft: false
          prerelease: false
          generate_release_notes: true
